INSERT INTO review (REVIEW_NOTE, REVIEW_DESCRIPTION, PRODUCT_ID_, USR_ID_) 
VALUES
(5, 'Service excellent, fortement recommandé.','1','11'),
(4, 'Bonne expérience globale. Pourrait s\'améliorer dans certains domaines.','2','12'),
(3, 'Service moyen. Place à l\'amélioration.','3','13'),
(5, 'Fantastique ! Reviendra certainement.','4','14'),
(2, 'Pas satisfait du service. Doit s\'améliorer.','4','12'),
(4, 'Excellent rapport qualité-prix.','5','12'),
(3, 'Expérience correcte, mais pas exceptionnelle.','2','18'),
(5, 'Personnel et installations incroyables.','5','11'),
(4, 'Très satisfait du service.','30','20'),
(2, 'Expérience décevante. Doit être grandement améliorée.','1','19'),
(4, 'Personnel amical et environnement propre.','27','19'),
(3, 'Correct, mais il y a de meilleures options disponibles.','14','16'),
(5, 'Service exceptionnel !','2','15'),
(4, 'Satisfait de l\'expérience globale.','14','11'),
(3, 'Service moyen, rien de spécial.','29','15'),
(5, 'Exceptionnel ! Recommanderais à d\'autres.','17','20'),
(4, 'Bon service, mais un peu cher.','26','11'),
(2, 'Expérience désagréable. Doit être considérablement améliorée.','13','13'),
(4, 'Content du service fourni.','6','20'),
(3, 'Pourrait être meilleur, mais pas terrible.','22','17');