INSERT IGNORE INTO product (product_name, PRODUCT_REF, ¨PRODUCT_AUTOR, PRODUCT_DES, PRODUCT_PICTURE, PRODUCT_STOCK, PRODUCT_PRICE, TYPE_ID,SPL_ID)
VALUES
("L'inconnue de la Seine","REF001","Guillaume Musso", "Par une nuit brumeuse de décembre, une jeune femme est repêchée dans la Seine au niveau du Pont-Neuf. Nue, amnésique, mais vivante.
Très agitée, elle est conduite à l'infirmerie de la préfecture de police de Paris. d\'où elle s'échappe au bout de quelques heures. Les analyses ADN et les photos révèlent son identité : il s'agit de la célèbre pianiste Milena Bergman. Mais c'est impossible, car Milena est morte dans un crash d'avion, il y a plus d'un an.
Rapahël, son ancien fiancé, et Roxane, une flic fragilisée par sa récente mise au placard, se prennent de passion pour cette enquête, bien décidés à éclaircir ce mystère : comment peut-on être à la fois morte et vivante ?
", "REF001picture", "30", "8.90","1","1"),
("Skidamarink","REF002","Guillaume Musso" ,"Introuvable depuis des années, le tout premier roman de Guillaume Musso enfin réédité !
Alors que le vol de La Joconde fait la une de tous les journaux, quatre personnes qui ne se connaissent pas reçoivent un fragment découpé de la célèbre œuvre de Léonard de Vinci, accompagné d'un mystérieux rendez-vous dans une chapelle de Toscane.
Pourquoi eux ? Qui les a choisis ? Quel plan se cache derrière ce coup d'éclat ? Ils l'ignorent encore, mais à l'instant même où ils décident de résoudre ensemble cette énigme, leur vie prend un tournant dangereux, exaltant et sans retour.
","REF002picture", "21", "8.90","1","1"),
("Marche ou Crève","REF003", "Stephen King","Garraty, un jeune adolescent natif du Maine, va concourir pour «\ La Longue Marche \», une compétition qui compte cent participants. Cet événement est très attendu. Il sera retransmis à la télévision, suivi par des milliers de personnes. Mais ce n’est pas une marche comme les autres, plutôt un jeu sans foi ni loi…
Garraty a tout intérêt à gagner. Le contraire pourrait lui coûter cher. Très cher…
", "REF003picture", "5", "12.90","1","1"),
("Le blé en herbe","REF004","Colette","Toute leur enfance les a unis, l'adolescence les sépare.Phil, 16 ans, et Vinca, 15 ans, amis de toujours, passent leurs étés en Bretagne. Tout naturellement, l'amour s'installe entre ces deux complices inséparables, un amour qui grandit plus vite qu'eux.Cet été-là, Vinca et Phil découvrent leurs différences et leurs incompréhensions. Ces amours adolescentes révèlent à Vinca et à Phil ce qu'ils sont désormais et ne seront jamais plus. Et ces vacances s'achèvent sur un adieu à l'enfance, amer et nostalgique avec délicatesse, Colette excelle à évoquer l'éveil de la sensualité, la douloureuse initiation à l'amour et à la vie.Ce roman a été adapté au cinéma par Claude Autant-Lara en 1954.", "REF004picture", "52", "7.90","1","2"),
("1991", "REF005","Franck Thilliez","La première enquête de Franck Sharko !Décembre 1991. Sur une photo : une femme couchée dans un lit, les mains attachées aux montants, la tête enfoncée dans un sac en papier marron. Au dos : une adresse écrite à la machine.
Quand le jeune inspecteur Franck Sharko, frais émoulu de l'école et novice au prestigieux 36, quai des Orfèvres, débarque sur les lieux, il découvre une scène de crime aussi insoutenable qu'incompréhensible.
Face à un mystère qui ne fera que s'épaissir au fil de l'enquête, Sharko sait que ses premières...
", "REF005picture", "2", "12.90","1","3"),
("Cujo","REF006", "Stephen King", "Cujo est un saint-bernard de cent kilos, le meilleur ami de Brett Camber, qui a dix ans. Un jour, Cujo chasse un lapin qui se réfugie dans une sorte de petite grotte souterraine habitée par des chauves-souris.
Ce qui va arriver à Cujo et à ceux qui auront le malheur de l’approcher constitue le sujet du roman le plus terrifiant que Stephen King ait jamais écrit. Brett et ses parents, leur voisin Vic Trenton et sa femme Donna, un couple en crise, Tad, leur petit garçon, en proie depuis des semaines à des terreurs nocturnes.
","REF006picture", "23", "8.90","1","1"),
("C'est arrivé la nuit","REF007","MARC Levy", "Ils sont hors-la-loi mais ils œuvrent pour le bien. Ils sont amis et partagent leurs secrets, affrontent les mêmes dangers, et pourtant ils ne se sont jamais rencontrés...
C'est arrivé la nuit, une course folle et terrifiante dans les rues d'Oslo, Madrid, Paris, Tel-Aviv, Istanbul et Londres. Et un pari dangereux : s'attaquer à la vilenie du monde.
", "REF007picture", "86", "11.90","1","1"),
("L'été Jonathan","REF008", "marie Dufeutreil", "Marik et sa bande de cousins-copains veillent jalousement sur l'organisation des vacances à la mer. Pas de temps à perdre quand il y a tant de choses à faire ! Aussi quand Jonathan, un petit garçon handicapé est invité à séjourner dans la maison familiale, Marik est bien décidée à ne pas se laisser encombrer par l'intrus. Mais Jonathan est là, et bien là, secret et apeuré.","REF008picture", "13", "8.90","1","1"),
("Jamais sans ma fille","REF009", "Betty Mahmoody", "Dans l'avion qui l'emmène à Téhéran avec son mari, d'origine iranienne, et sa fille, Betty a le sentiment d'avoir commis une erreur irréparable...
Quelques jours plus tard, son existence bascule dans le cauchemar. Le verdict tombe : Tu ne quitteras jamais l'Iran ! Tu y resteras jusqu'à ta mort. En proie au fanatisme religieux, son mari se transforme en geôlier.
Elle n'a désormais qu'un objectif : rentrer chez elle, aux États-Unis, avec sa fille. Quitter ce monde incohérent où la femme n'existe pas.
Pour reconquérir sa liberté, Betty mènera deux ans de lutte incessante. Humiliations, séquestration, chantage, violences physiques et morales. Rien ne lui sera épargné.
","REF009picture", "30", "8.90","1","1"),
("Pour rien au monde","REF010","Ken Follet", "De nos jours, dans le désert du Sahara, deux agents secrets français et américain pistent des terroristes trafiquants de drogue, risquant leur vie à chaque instant. Une jeune veuve tente de rejoindre l'Europe et se bat contre des passeurs. Elle est aidée par un homme mystérieux qui cache sa véritable identité. En Chine, un membre du gouvernement lutte contre de vieux faucons communistes qui poussent le pays vers un point de non-retour. Aux États-Unis, la première femme élue présidente doit manœuvrer entre des attaques au Sahel, le commerce illégal d'armes et les bassesses d'un rival politique.
Alors que des actions violentes se succèdent partout dans le monde, les grandes puissances se débattent dans des alliances complexes. Pourront-elles empêcher l'inévitable ?
","REF010picture", "31", "8.90","1","2"),
("Criminel le mal au féminin","REF011","Pierre Bellemare", "Vous reconnaîtrez ainsi les figures emblématiques du Mal au féminin, comme Catherine Deshayes, dite La Voisine, qui organisa des messes noires où l'on sacrifiait des nourrissons pour le compte de Mme de Montespan, la célèbre Lucrèce Borgia, grande empoisonneuse de l'empire romain, ou encore Isle Koch, surnommée la chienne de Buchenwald...

Et vous découvrirez aussi quelques tueuses moins connues mais tout aussi cruelles et glaçantes, comme Erzébeth Bathory qui tua ou fit tuer plusieurs centaines de jeunes vierges pour se baigner dans leur sang en vue de conserver une peau douce dans la Hongrie du XVIe siècle, ou encore l'incroyable Ching Shih, la plus grande pirate de tous les temps, qui régna sur la mer de Chine. Découvrez le destin hors du commun de ces femmes passées maîtresses dans l'art de tuer.
","REF011picture", "10", "8.90","1","2"),
("Histoire choc","REF012","Pierre Bellemare", "Au nom de Pierre Bellemare, c'est tout un cortège d'histoires vraies qui surgit en séquences inoubliables. Bellemare c'est un monument et c'est un mémorial. Par la voix, par la plume et par l'image, le plus célèbre conteur français nous invite au grand film de la vie. Du rose au noir, de la joie au désespoir, c'est l'histoire de notre temps qu'il restitue, sans artifice, dans son nouveau livre. Histoires Choc, c'est 80 événements sélectionnés par Pierre Bellemare. Dans la grande tradition de ses dossiers extraordinaires on y trouve, rassemblés en récits courts et nerveux, les faits marquants des quarante dernières années. Des exploits, des coups de cœur et des drames. Bellemare nous conduit ainsi au mur de Berlin, aux Jeux de la haine à Munich, des 24h du Mans sanglants de 1955 à la tragédie du 5-7, le dancing incendié. Il nous raconte l'enlèvement du baron Empain et celui de Paul Getty Jr. Et nous entraîne dans la légende des grandes stars qui ne mourront jamais : James Dean et Marylin. 80 histoires vraies. 40 ans d'histoires choc.","REF012picture", "2", "8.90","1","1"),
("Brulée vive","REF013","Souad", "Souad a dix-sept ans, elle est amoureuse. Dans son village l'amour avant le mariage est synonyme de mort. Déshonorée , sa famille désigne son beau-frère pour exécuter la sentence.
Aux yeux de tous, cet homme est un héros. C'est ce que l'on appelle un crime d'honneur . Ce n'est en fait qu'un lâche assassinat.
Atrocement brûlée, Souad a été sauvée par miracle. Elle a décidé de parler pour toutes celles qui aujourd'hui risquent leur vie.
","REF013picture", "8", "8.90","1","3"),
("127 heures ","REF014","Aron Ralston", "Le 26 avril 2003, Aron Ralston, 27 ans, se met en route pour une randonnée dans les gorges de l'Utah. Alpiniste expérimenté, il est déjà venu à bout des plus hauts sommets de la région. Là, au fond d'un canyon reculé, l'impensable survient : un rocher se détache au-dessus de lui et emprisonne son bras dans un mur de rocaille. Le voilà pris au piège. 127 heures plus tard, comprenant que les secours n'arriveront pas, il va devoir prendre la décision la plus difficile de son existence...","REF014picture", "30", "8.90","1","3"),
("Dragon Ball tome 1","REF015","Toriyama Akira","Les dragon balls sont des boules de cristal magiques. Celui qui les réunit invoque un dragon qui réalisera ses voeux. Sangoku, Dendé, Végéta et tous les protagonistes de cette grande saga tentent de trouver les sept dragon balls qui, une fois le voeu exaucé, s'éparpilleront à nouveau dans l'univers.
Devenue un véritable phénomène de mode dès sa parution, cette série connaît un succès mondial auprès de toute une génération.
", "REF015picture", "20", "8.90","2","3"),
("Dragon Ball tome 2","REF016","Toriyama Akira", "Les dragon balls sont des boules de cristal magiques. Celui qui les réunit invoque un dragon qui réalisera ses voeux. Sangoku, Dendé, Végéta et tous les protagonistes de cette grande saga tentent de trouver les sept dragon balls qui, une fois le voeu exaucé, s'éparpilleront à nouveau dans l'univers.Devenue un véritable phénomène de mode dès sa parution, cette série connaît un succès mondial auprès de toute une génération.","REF016picture", "20", "8.90","2","3"),
("Dragon Ball tome 3","REF017","Toriyama Akira", "Les dragon balls sont des boules de cristal magiques. Celui qui les réunit invoque un dragon qui réalisera ses voeux. Sangoku, Dendé, Végéta et tous les protagonistes de cette grande saga tentent de trouver les sept dragon balls qui, une fois le voeu exaucé, s'éparpilleront à nouveau dans l'univers.Devenue un véritable phénomène de mode dès sa parution, cette série connaît un succès mondial auprès de toute une génération.","REF017picture", "20", "8.90","2","2"),
("City Hunter tome 1 ","REF018","Tsukasa Hojo", "City Hunter est le manga original qui a inspiré le dessin animé Nicky Larson. Dans ce premier tome, on découvre Ryo Saeba (qui est surnommé City Hunter), un nettoyeur qui oeuvre en collaboration avec son ami Hideyuki Makimura. Leurs clients sont divers et variés : l'épouse d'un boxer qui s'est fait assassiné, la soeur d'une jeune femme qui a été enlevée… Nos deux compères ont donc pour but de venger ces victimes de leurs effroyables bourreaux.","REF018picture", "1", "8.90","2","2"),
("Cat's eye","REF019","Tsukasa Hojo", "Rui, Hitomi et Ai Kisugi sont soeurs. Gérantes du café Cats Eye le jour ; elles enfilent, la nuit venue, des tenues de cambrioleuses et se faufilent dans les musées pour voler des oeuvres dart. La police est toujours prévenue de leurs futurs méfaits, d’une carte signée Cats Eye...","REF019picture", "1", "8.90","2","1"),
("La bible officielle de cookeo","REF020","Séverine Augé", "200 recettes courtes et rapides à réaliser, avec :Des ingrédients faciles à trouverDes infos pour adapter au mieux vos menusLes modes de programmation de l'appareil visibles en un clin d'oeil Avec votre cookeo, régalez-vous de l'apéro au dessert !","REF020picture", "10", "8.90","3","2"),
("La nouvelle chrononutrition","REF021","Alain Delabosse", "Vous êtes en surpoids et vous avez des formes en trop ? Vous voulez bien manger tout en respectant vos rythmes biologiques ? Imaginez donc une méthode d'alimentation naturelle qui vous permettra de perdre du poids et retrouver une silhouette idéale en mangeant tout ce que vous voulez ! C'est ce que propose le docteur Alain Delabos.
Oui, le fromage, les frites ou le chocolat seront autorisés dans votre programme car la Chrononutrition n'est pas un régime mais une méthode de réorganisation des repas.
Faisant le constat que notre corps sécrète certaines hormones et libère des enzymes à des heures précises de la journée, le docteur Alain Delabos a créé, il y a plus de 30 ans, la Chrononutrition, une méthode autorisant à manger ce que l'on veut, mais pas n'importe comment ni n'importe quand !
les gras saturés (fromage par exemple) en exclusivité le matin,
les viandes et les féculents le midi, une pause sucrée, au goûter ,poissons ou fruits de mer à volonté, viandes blanches et légumes verts en quantité raisonnable, le soir.
","REF021picture", "30", "8.90","3","3"),
("Harry Potter à l'école des sourciers","REF022","J.k Rowling","Le jour de ses onze ans, Harry Potter, un orphelin élevé par un oncle et une tante qui le détestent, voit son existence bouleversée. Un géant vient le chercher pour l'emmener à Poudlard, une école de sorcellerie ! Voler en balai, jeter des sorts, combattre les trolls : Harry révèle de grands talents. Mais un mystère entoure sa naissance et l'effroyable V., le mage dont personne n'ose prononcer le nom.", "REF022picture", "8", "8.90","1","3"),
("Harry Potter et la chambre des secrets ","REF023", "J.K Rowling","Une rentrée fracassante en voiture volante, une étrange malédiction qui s'abat sur les élèves, cette deuxième année à l'école des sorciers ne s'annonce pas de tout repos ! Entre les cours de potions magiques, les matchs de Quidditch et les combats de mauvais sorts, Harry et ses amis Ron et Hermione trouveront-ils le temps de percer le mystère de la Chambre des Secret","REF023picture", "3", "8.90","1","1"),
("Harry Potter et le prisonnier d'Azcaban ","REF024", "J.K Rowling","
Depuis douze longues années, l'infâme criminel Sirius Black, partisan de Lord Voldemort et reconnu coupable d'avoir tué treize personnes d'un coup, était enfermé dans la forteresse d'Azkaban. Mais il s'est évadé et il recherche Harry Potter. Les gardiens de la prison l'ont entendu murmurer dans son sommeil : Il est à Poudlard... Malgré les défenses magiques de l'école de sorcellerie, Harry Potter n'est en sécurité nul part, même entouré de ses amis... car un traitre pourrait bien se cacher parmi eux.
","REF024picture", "3", "8.90","1","2"),
("Harry Potter et la coupe de feu ","REF025", "J.K Rowling","Harry Potter a quatorze ans et entre en quatrième année à Poudlard. Une grande nouvelle attend Harry, Ron et Hermione à leur arrivée : la tenue d'un tournoi de magie exceptionnel entre les plus célèbres écoles de sorcellerie. Déjà les délégations étrangères font leur entrée. Harry se réjouit... Trop vite. Il va se trouver plongé au coeur des événements les plus dramatiques qu'il ait jamais eu à affronter.","REF025picture", "3", "8.90","1","1"),
("Le grand livre des DIY","REF026","Emilie Guelpa", "Cet ouvrage regroupe plus de 150 DIY (Do it yourself) autour des matières  : marbre, béton, textile, bois, verre... pour réaliser des petits bijoux, objets, accessoires et autres décorations.
Toutes les techniques expliquées pas à pas. Des créations très tendance. Pour les débutants comme les plus expérimentés.
","REF026picture", "23", "8.90","3","1"),
("La guerre invisible","REF027","Leila Minano", "La fin du service militaire en 1997 a bouleversé son recrutement. Mais on ne change pas les mentalités du jour au lendemain. Dans ce monde clos et viril, des soldates endurent en silence des violences sexuelles, verbales ou physiques .Une enquête inédite au sein de l'armée de Terre, de l'armée de l'Air et de la Marine, dans la Gendarmerie et jusqu'en opération extérieure au Mali.","REF027picture", "30", "8.90","1","1"),
("Mauvaise troupe","REF028", "Leila Minano","De flamboyantes campagnes de pub les ont attirés. Ils affrontent une tout autre réalité. Enquête sur de jeunes recrues à bout de nerfs.
Depuis les attentats de 2015, l'armée française recrute large. Avec 1,7 candidat seulement par poste de militaire du rang, elle n'a guère de choix. Ces volontaires fuient souvent l'échec scolaire, le chômage ou la petite délinquance et rêvent d'une guerre de jeu vidéo. Puis ils découvrent l'absurdité des patrouilles Sentinelle, les conditions de vie déplorables et l'indécision du commandement. Mal préparés aux atrocités de la guerre, ils sont envoyés au Mali ou en Centrafrique. Accros aux réseaux sociaux, aux drogues, à l'alcool, certains ont dérapé jusqu'à commettre des exactions sur des civils centrafricains.
Mauvaise troupe décrit l'existence de ces soldats déboussolés, abandonnés à leur errance par une hiérarchie dépassée. Cette enquête de terrain, étayée par des documents internes exclusifs, dévoile enfin une réalité occultée.
","REF028picture","2", "8.90","1","3"),
("L'armée au féminin","REF029", "Jean Marc Tanguy","Depuis la guerre du Golfe, les femmes ont réussi à s’imposer dans presque tous les secteurs de la vie militaire, et notamment en opérations. Pilotes de la Marine et de l’armée de l’air, personnels des forces spéciales, commandos parachutistes, infirmières et médecins, mécaniciennes, maîtres-chiens, expertes du renseignement… ce livre détaille, par le biais de portraits et de témoignages, les différentes spécialités qu’elles occupent aujourd’hui. Il fait, pour la première fois, découvrir cette richesse insoupçonnable que constitue cette armée au féminin.
Journaliste, Jean-Marc Tanguy est un spécialiste français de l’histoire militaire, notamment dans le domaine de l’aviation mais également spécialiste des unités d’élite. Il est d’ailleurs l’auteur de dix livres, comme son ouvrage sur Le RAID, ou Les Commandos parachutistes de l'Air.
","REF029picture", "12", "8.90","1","2"),
("La bible des huiles essentielles","REF030","Danièle Festy", "Découvrez le fabuleux potentiel des huiles essentielles pour votre santé, votre beauté, votre bien-être, pour une maison plus saine et plus agréable, et une cuisine plus digeste et plus parfumée !
Dans cette bible illustrée :
•	Apprivoisez les 75 huiles essentielles les plus efficaces : lavande officinale, tea tree, romarin à cinéole, gaulthérie couchée, hélichryse italienne, ylang-ylang… à chacune ses propriétés, ses indications, ses voies d’administration.
•	À respirer, à avaler, à diffuser, à appliquer sur la peau en compresses, en massages ou dans le bain, plus de 1 100 formules personnalisées pour traiter 250 maux du quotidien.
•	700 massages et applications illustrés pour vous soigner vite, bien et sans risque, avec les huiles essentielles.
•	Toutes les idées bien-être pour profiter des huiles essentielles à la maison et vos cosmétiques 100 % naturels.
•	10 trousses personnalisées, pour avoir toujours sous la main les flacons indispensables : enfants, futures mamans, seniors… à chacun ses  essentiels.
","REF030picture", "28", "15.90","3","2")
ON DUPLICATE KEY UPDATE product_name = VALUES(product_name), ¨PRODUCT_AUTOR = VALUES(¨PRODUCT_AUTOR), PRODUCT_DES = VALUES(PRODUCT_DES), PRODUCT_PICTURE = VALUES(PRODUCT_PICTURE), PRODUCT_STOCK = VALUES(PRODUCT_STOCK), PRODUCT_PRICE = VALUES(PRODUCT_PRICE), TYPE_ID = VALUES(TYPE_ID), SPL_ID = VALUES(SPL_ID);


