CREATE TABLE CLIENT_(
   USR_ID_ INT AUTO_INCREMENT,
   USER_FIRSTNAME VARCHAR(50),
   USER_LASTNAME VARCHAR(50),
   USER_MAIL VARCHAR(50),
   USER_PASSWORD VARCHAR(255),
   PRIMARY KEY(USR_ID_)
);

CREATE TABLE SUPPLIER(
   SPL_ID INT AUTO_INCREMENT,
   SPL_NAME VARCHAR(50),
   PRIMARY KEY(SPL_ID)
);

CREATE TABLE TYPE(
   TYPE_ID INT AUTO_INCREMENT,
   TYPE_CATEGORIE VARCHAR(50),
   PRIMARY KEY(TYPE_ID)
);

CREATE TABLE STORY_ORDER(
   STORY_ID INT AUTO_INCREMENT,
   ORDER_DATE VARCHAR(50),
   ORDER_REF VARCHAR(50),
   USR_ID_ INT NOT NULL,
   PRIMARY KEY(STORY_ID),
   FOREIGN KEY(USR_ID_) REFERENCES CLIENT_(USR_ID_)
);

CREATE TABLE PRODUCT(
   PRODUCT_ID_ INT AUTO_INCREMENT,
   PRODUCT_DESCRIPTION VARCHAR(100),
   PRODUCT_PICTURE VARCHAR(50),
   PRODUCT_STOCK INT,
   PRODUCT_PRICE DECIMAL(9,2),
   PRODUCT_REF VARCHAR(50),
   TYPE_ID INT NOT NULL,
   SPL_ID INT NOT NULL,
   PRIMARY KEY(PRODUCT_ID_),
   FOREIGN KEY(TYPE_ID) REFERENCES TYPE(TYPE_ID),
   FOREIGN KEY(SPL_ID) REFERENCES SUPPLIER(SPL_ID)
);

CREATE TABLE REVIEW(
   REVIEW_ID INT AUTO_INCREMENT,
   REVIEW_NOTE INT,
   REVIEW_DESCRIPTION VARCHAR(50),
   PRODUCT_ID_ INT NOT NULL,
   USR_ID_ INT NOT NULL,
   PRIMARY KEY(REVIEW_ID),
   FOREIGN KEY(PRODUCT_ID_) REFERENCES PRODUCT(PRODUCT_ID_),
   FOREIGN KEY(USR_ID_) REFERENCES CLIENT_(USR_ID_)
);

CREATE TABLE TO_POSSESS(
   PRODUCT_ID_ INT,
   STORY_ID INT,
   PRIMARY KEY(PRODUCT_ID_, STORY_ID),
   FOREIGN KEY(PRODUCT_ID_) REFERENCES PRODUCT(PRODUCT_ID_),
   FOREIGN KEY(STORY_ID) REFERENCES STORY_ORDER(STORY_ID)
);

